### ISSUE TITLE
Pusher key exposed

### ISSUE THREAD

**Issue by kseistrup** [leplatrem/kinto-telegram-wall#13]
Pusher key is exposed in [script.js](https://leplatrem.github.io/kinto-telegram-wall/script.js):

``` js
  // Pusher app key
  var pusher_key = "01a9feaaf9ebb120d1a6";
```

is this intentional?

**Comment by Natim** [comment]
Yes :) This key let you subscribe to pusher public channels for the kinto.dev demo server.

**Comment by kseistrup** [comment]
Well, yes, but if I wish to run my own “telegram wall”, would I also want to make this key world readable?

**Comment by leplatrem** [comment]
Yes that's the only way for the frontend application to know which channel to subscribe.

However, Pusher provides a way to have authenticated channels. But we didn't implemented yet (mentionned in todo here https://github.com/leplatrem/cliquet-pusher#todo)

**Comment by kseistrup** [comment]
Thanks.

I guess I should close this issue then. :smile:
